### PR TITLE
revised to include register button

### PR DESCRIPTION
**Pull request by Darwinny**

### CODE REVIEW

**Comment by ghost** [comment]
Is this finished? I don't have the permissions to merge this, but the source looks good to me...

**Comment by Darwinny** [comment]
This is weird . . .I think it is on my own copy of Pubbly-2016. . . . just grab it . . . it's done.

My set up is different now . . . shouldn't happen again

**Comment by Darwinny** [comment]
if you want me to branch it off what I have now . . . I can. Let me know

**Comment by ghost** [comment]
Maybe do that... I'm still seeing a message that reads

> This branch has no conflicts with the base branch
> Only those with write access to this repository can merge pull requests.

**Comment by ghost** [comment]
If all else fails, send me a zip.

**Pull request closed without merging**
